### PR TITLE
Upgrade p4d and swarm to 2022.2

### PR DESCRIPTION
**Pull request by peterguy**

### CODE REVIEW

**Comment by thejustinwalsh** [comment]
👋 @unknwon Any chance we can get this PR merged and a new version pushed up to dockerhub?

**Comment by thejustinwalsh** [comment]
btw, It looks like 2023.1 is out now as well.
https://www.perforce.com/support/software-release-index

**Comment by unknwon** [comment]
Thanks @peterguy and sorry that I am not actively monitoring this repository, I'll update this PR.

**Comment by unknwon** [comment]
I'm waiting for push access to the Docker Hub repo.

**Comment by unknwon** [comment]
Both `2023.1` and `latest` image tags are upserted.

**Comment by thejustinwalsh** [comment]
Amazing! Thank you!

**Pull request merged**
