### PR TITLE
update helix-p4d to 2024.1

### PR DESCRIPTION
**Pull request by catpreneur**

### CODE REVIEW

**Comment by catpreneur** [comment]
@burmudar

**Comment by burmudar** [comment]
Taking a look

**Comment by burmudar** [comment]
Verified it starts up
```
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::
::  P4D configuration has completed successfully.
::
::  Here is what has been done so far:
::
::  - Your p4d service settings have been written to
::    the following p4dctl configuration file:
::      /etc/perforce/p4dctl.conf.d/perforce-server.conf
::  - The p4d service has been initialized with the P4ROOT:
::      /p4/root/root
::  - The p4d service has been started with the P4PORT: 1666
::  - The p4d service has been set to Security Level 3.
::  - The new Perforce super-user 'admin' has been created and the
::    password has been set to the one specified.
::
::  Here is what you can do now:
::
::  - You can manage it with the 'perforce' user, using the following:
::
::      sudo -u perforce p4dctl <cmd>
::
::  - You can connect to it by setting the P4PORT and P4USER
::    environment variables and running 'p4 <cmd>'. For example, run:
::
::      export P4PORT=1666
::      export P4USER=admin
::
::      p4 login
::
::    For help, run:
::
::      p4 help
::
::  - For help with creating Perforce Helix user accounts, populating
::    the depot with files, and making other customizations for your
::    site, see the Helix Versioning Engine Administrator Guide:
::
::    https://www.perforce.com/perforce/doc.current/manuals/p4sag/index.html
::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by burmudar** [comment]
Hey @doggge77 forgot to mention this but thanks for the contribution!

**Pull request merged**
