### PR TITLE
Add instructions for running with SSL enabled

### PR DESCRIPTION
**Pull request by eseliger**
Just some addition for the docs on how to use SSL with this image.

### CODE REVIEW

**Comment by eseliger** [comment]
cc @peterguy, somehow github doesn't let me pick you as a reviewer 😓

**Comment by unknwon** [comment]
> cc @peterguy, somehow github doesn't let me pick you as a reviewer 😓

'cause he has no write access

**Review by unknwon — APPROVED** [review]

**Comment by peterguy** [comment]
Write access or not, this is a great update! :-)

**Pull request merged**
