### PR TITLE
Upgrade p4d and swarm to 2023.2

### PR DESCRIPTION
**Pull request by Stealthii**
Updates both primary packages to the `2023.2` base versions.

### CODE REVIEW

**Comment by disastercurl** [comment]
It's worth mentioning that packages like `helix-swarm-triggers` have a 2023.4 version already, whereas the base p4d does not - it might be worth staging an update to the `latest` tag with up-to-date packages across the board, as dependencies also don't have any version pinning.

**Comment by burmudar** [comment]
Hey @Stealthii - Apologies for not accepting your PR. This is totally on us - For us to be able to accept your PR you have to have had to sign the CLA. We usually have a bot that notifies people but it is absent on this repo

**Comment by TheExeQ** [comment]
Seems like the are some problems with installing the packages, or is it only for me? 🤔 
```
=> ERROR [3/8] RUN apt-get update && apt-get install -y helix-p4d=2023.2-2523307~focal helix-swarm-triggers=2023.4-2531655~focal                                                     1.8s
------
 > [3/8] RUN apt-get update && apt-get install -y helix-p4d=2023.2-2523307~focal helix-swarm-triggers=2023.4-2531655~focal:
0.282 Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0.306 Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
0.337 Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
0.366 Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
0.530 Hit:5 http://package.perforce.com/apt/ubuntu focal InRelease
0.574 Reading package lists...
1.155 Reading package lists...
1.652 Building dependency tree...
1.739 Reading state information...
1.750 E: Unable to locate package helix-p4d
1.750 E: Unable to locate package helix-swarm-triggers
------
Dockerfile:24
--------------------
  22 |     # Do in-page search over https://package.perforce.com/apt/ubuntu/dists/focal/release/binary-amd64/Packages
  23 |     # for both "Package: helix-p4d" and "Package: helix-swarm-triggers".
  24 | >>> RUN apt-get update && apt-get install -y helix-p4d=2023.2-2523307~focal helix-swarm-triggers=2023.4-2531655~focal
  25 |     # Add external files
  26 |     COPY files/restore.sh /usr/local/bin/restore.sh
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get update && apt-get install -y helix-p4d=2023.2-2523307~focal helix-swarm-triggers=2023.4-2531655~focal" did not complete successfully: exit code: 100
```

**Comment by burmudar** [comment]
> Seems like the are some problems with installing the packages, or is it only for me? 🤔 
> 
> ```
> 
> => ERROR [3/8] RUN apt-get update && apt-get install -y helix-p4d=2023.2-2523307~focal helix-swarm-triggers=2023.4-2531655~focal                                                     1.8s
> 
> ------
> 
>  > [3/8] RUN apt-get update && apt-get install -y helix-p4d=2023.2-2523307~focal helix-swarm-triggers=2023.4-2531655~focal:
> 
> 0.282 Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
> 
> 0.306 Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
> 
> 0.337 Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
> 
> 0.366 Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
> 
> 0.530 Hit:5 http://package.perforce.com/apt/ubuntu focal InRelease
> 
> 0.574 Reading package lists...
> 
> 1.155 Reading package lists...
> 
> 1.652 Building dependency tree...
> 
> 1.739 Reading state information...
> 
> 1.750 E: Unable to locate package helix-p4d
> 
> 1.750 E: Unable to locate package helix-swarm-triggers
> 
> ------
> 
> Dockerfile:24
> 
> --------------------
> 
>   22 |     # Do in-page search over https://package.perforce.com/apt/ubuntu/dists/focal/release/binary-amd64/Packages
> 
>   23 |     # for both "Package: helix-p4d" and "Package: helix-swarm-triggers".
> 
>   24 | >>> RUN apt-get update && apt-get install -y helix-p4d=2023.2-2523307~focal helix-swarm-triggers=2023.4-2531655~focal
> 
>   25 |     # Add external files
> 
>   26 |     COPY files/restore.sh /usr/local/bin/restore.sh
> 
> --------------------
> 
> ERROR: failed to solve: process "/bin/sh -c apt-get update && apt-get install -y helix-p4d=2023.2-2523307~focal helix-swarm-triggers=2023.4-2531655~focal" did not complete successfully: exit code: 100
> 
> ```

Hey @TheExeQ, I got a similar error when I built this initially. I assume you're building this on darwim? Either way you need to pass `--platform linux/amd64` as part of the docker build command. I have also added a `build.sh` script in the Dockerfile directory which will do this 🙂

**Comment by burmudar** [comment]
Closing this as we've already updated this :)

**Pull request closed without merging**
